In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np
data_path = "/home/aquib/Desktop/Iris.csv"

In [3]:
def read_data():
    data = pd.read_csv(data_path)
    x_lables = np.array(data.iloc[0:150,[1,2,3,4]].values)
    y_lable = data.iloc[0:150,[5]].values
    
    y = []
    value = []
    for i in y_lable:
        if i not in value:
            value.append(i)

    for i in y_lable:
        y.append(value.index(i))
        
    y_lable = pd.get_dummies(y)
    return x_lables,y_lable

    
read_data()

(array([[ 5.1,  3.5,  1.4,  0.2],
        [ 4.9,  3. ,  1.4,  0.2],
        [ 4.7,  3.2,  1.3,  0.2],
        [ 4.6,  3.1,  1.5,  0.2],
        [ 5. ,  3.6,  1.4,  0.2],
        [ 5.4,  3.9,  1.7,  0.4],
        [ 4.6,  3.4,  1.4,  0.3],
        [ 5. ,  3.4,  1.5,  0.2],
        [ 4.4,  2.9,  1.4,  0.2],
        [ 4.9,  3.1,  1.5,  0.1],
        [ 5.4,  3.7,  1.5,  0.2],
        [ 4.8,  3.4,  1.6,  0.2],
        [ 4.8,  3. ,  1.4,  0.1],
        [ 4.3,  3. ,  1.1,  0.1],
        [ 5.8,  4. ,  1.2,  0.2],
        [ 5.7,  4.4,  1.5,  0.4],
        [ 5.4,  3.9,  1.3,  0.4],
        [ 5.1,  3.5,  1.4,  0.3],
        [ 5.7,  3.8,  1.7,  0.3],
        [ 5.1,  3.8,  1.5,  0.3],
        [ 5.4,  3.4,  1.7,  0.2],
        [ 5.1,  3.7,  1.5,  0.4],
        [ 4.6,  3.6,  1. ,  0.2],
        [ 5.1,  3.3,  1.7,  0.5],
        [ 4.8,  3.4,  1.9,  0.2],
        [ 5. ,  3. ,  1.6,  0.2],
        [ 5. ,  3.4,  1.6,  0.4],
        [ 5.2,  3.5,  1.5,  0.2],
        [ 5.2,  3.4,  1.4,  0.2],
        [ 4.7,

In [5]:
x_lables, y_lable = read_data()

X_input = tf.placeholder(tf.float32, [None,4])
y_output = tf.placeholder(tf.float32, [None,3])


w1 = tf.Variable(tf.random_normal([4,5]), name = "Weights_1")
b1 = tf.Variable(tf.random_normal([1,5]), name = "Bias_1")

w2 = tf.Variable(tf.random_normal([5,3]),  name = "Weights_2")
b2 = tf.Variable(tf.random_normal([1,3]), name = "Bias_2")
#print "weight_2 before Iteration: ",w2

In [18]:
hidden_layer = tf.nn.sigmoid(tf.matmul(X_input,w1)+b1)
output_layer = tf.nn.softmax(tf.matmul(hidden_layer,w2) + b2)

losses = tf.losses.mean_squared_error(y_lable,output_layer)

#optimizer = tf.train.AdamOptimizer(0.001).minimize(losses)
optimizer = tf.train.GradientDescentOptimizer(0.09).minimize(losses)

sess = tf.InteractiveSession()
init = tf.global_variables_initializer()
sess.run(init)
print "************************weights before training*********************************"
print "                                                                                "
we1,we2 = sess.run([w1,w2])
print "weight_1: "
print we1
print "weight_2: "
print we2

print "-------------------------Training Result------------------------------------------"
print "                                                                                 "

step_size = 10000
for step in range(step_size):
    
    a,b,c,d,e,f = sess.run([hidden_layer,output_layer,losses,optimizer,w1,w2], feed_dict={X_input:x_lables,y_output:y_lable})
    
    if step%2000==0:
        
        print "losses after per 1000 iteration: ",c

check = tf.nn.sigmoid(tf.matmul([[6.8,3.2,5.9,2.3]],w1)+b1)
output = tf.nn.softmax(tf.matmul(check,w2) + b2)

print "*****************************weight after training*************************************"
print "weight_1 after trainig: "
print e
print "weight_2 after training: "
print f

a,b = sess.run([check,output])
#print (output)
print "-------------------------------------Results--------------------------------------------"
print "                                                                                         "
print "Result:  ",b


************************weights before training*********************************
                                                                                
weight_1: 
[[ -4.17683423e-01   1.26511633e+00   4.24637258e-01   1.15733683e+00
   -7.54366755e-01]
 [ -1.41512227e+00  -7.60820210e-01   4.09764834e-02  -4.73701328e-01
    1.16874361e+00]
 [ -8.04364011e-02  -9.50930238e-01   1.73865934e-03  -3.24605741e-02
    8.00050795e-01]
 [  8.83699834e-01  -2.74147034e-01   4.52570349e-01   2.05774975e+00
   -5.05107582e-01]]
weight_2: 
[[-0.87454176 -0.77493054  1.32994819]
 [-0.81558901  0.61828578  0.37749916]
 [ 1.09900236 -0.40082777  0.4573271 ]
 [ 0.78624749 -0.75187039 -0.02564553]
 [ 0.80824882 -0.80396068  1.24323571]]
-------------------------Training Result------------------------------------------
                                                                                 
losses after per 1000 iteration:  0.319213
losses after per 1000 iteration:  0.0803356
losses 