In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
data_path = "/home/aquib/Desktop/Iris.csv"

In [5]:
def read_data():
    data = pd.read_csv(data_path) #read the data
    data = data.reindex(np.random.permutation(data.index)) #shuffling the data

    x_lables = np.array(data.iloc[0:150,[1,2,3,4]].values) 
    y_lable = data.iloc[0:150,[5]].values
    
    y = []
    value = []
    for i in y_lable:
        if i not in value:
            value.append(i)

    for i in y_lable:
        y.append(value.index(i))
        
    y_lable = pd.get_dummies(y)
    return x_lables,y_lable

    
read_data()

(array([[ 6.7,  3. ,  5. ,  1.7],
        [ 6.9,  3.1,  4.9,  1.5],
        [ 5.8,  2.7,  5.1,  1.9],
        [ 5.8,  2.7,  5.1,  1.9],
        [ 4.8,  3.1,  1.6,  0.2],
        [ 5.5,  2.5,  4. ,  1.3],
        [ 6.4,  2.8,  5.6,  2.2],
        [ 6.5,  3. ,  5.5,  1.8],
        [ 4.4,  3.2,  1.3,  0.2],
        [ 5.6,  3. ,  4.1,  1.3],
        [ 4.6,  3.1,  1.5,  0.2],
        [ 7.1,  3. ,  5.9,  2.1],
        [ 5.2,  3.5,  1.5,  0.2],
        [ 4.6,  3.4,  1.4,  0.3],
        [ 6.3,  2.8,  5.1,  1.5],
        [ 5. ,  2.3,  3.3,  1. ],
        [ 5.8,  2.6,  4. ,  1.2],
        [ 7.3,  2.9,  6.3,  1.8],
        [ 7.2,  3.2,  6. ,  1.8],
        [ 6.1,  2.8,  4.7,  1.2],
        [ 6.4,  2.7,  5.3,  1.9],
        [ 5. ,  3. ,  1.6,  0.2],
        [ 6.1,  3. ,  4.6,  1.4],
        [ 4.8,  3.4,  1.6,  0.2],
        [ 7.2,  3.6,  6.1,  2.5],
        [ 6. ,  3.4,  4.5,  1.6],
        [ 5.6,  2.8,  4.9,  2. ],
        [ 6.1,  3. ,  4.9,  1.8],
        [ 6.3,  3.3,  4.7,  1.6],
        [ 7.9,

In [6]:
x_lables, y_lable = read_data()

X_input = tf.placeholder(tf.float32, [None,4]) #creating palce holder for the holding the input value data will be feed during runtime
y_output = tf.placeholder(tf.float32, [None,3]) #creating placeholder for holding the actual label the data will feed during the run time


w1 = tf.Variable(tf.random_normal([4,5]), name = "Weights_1") #Initaliazing weight_1
b1 = tf.Variable(tf.random_normal([1,5]), name = "Bias_1")

w2 = tf.Variable(tf.random_normal([5,3]),  name = "Weights_2") #Initaliazing weight_2
b2 = tf.Variable(tf.random_normal([1,3]), name = "Bias_2")
#print "weight_2 before Iteration: ",w2

In [7]:
hidden_layer = tf.nn.sigmoid(tf.matmul(X_input,w1)+b1) 
output_layer = tf.nn.softmax(tf.matmul(hidden_layer,w2) + b2)

losses = tf.losses.mean_squared_error(y_lable,output_layer)

#optimizer = tf.train.AdamOptimizer(0.001).minimize(losses)
optimizer = tf.train.GradientDescentOptimizer(0.09).minimize(losses)

sess = tf.InteractiveSession()
init = tf.global_variables_initializer()
sess.run(init)
print "************************weights before training*********************************"
print "                                                                                "


we1,we2 = sess.run([w1,w2])
print "weight_1: "
print we1
print "weight_2: "
print we2

print "-------------------------Training Result------------------------------------------"
print "                                                                                 "

step_size = 10000
for step in range(step_size):
    
    a,b,c,d,e,f = sess.run([hidden_layer,output_layer,losses,optimizer,w1,w2], feed_dict={X_input:x_lables,y_output:y_lable})

    if step%2000==0:
        print "losses after per 1000 iteration: ",c

print "                                                                                         "       
correct_prediction = tf.equal(tf.argmax(output_layer,1), tf.argmax(y_output,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print "-------------------------------------Accuracy--------------------------------------------"
print "                                                                                         "

print "Accuracy on the model: ",accuracy.eval(feed_dict={X_input:x_lables, y_output:y_lable})

check = tf.nn.sigmoid(tf.matmul([[6.8,3.2,5.9,2.3]],w1)+b1)
output = tf.nn.softmax(tf.matmul(check,w2) + b2)

print "***************************** weight after training *************************************"
print "weight_1 after trainig: "
print e
print "weight_2 after training: "
print f

a,b = sess.run([check,output])
#print (output)
print "-------------------------------------Results--------------------------------------------"
print "                                                                                         "
print "Result:  ",b


************************weights before training*********************************
                                                                                
weight_1: 
[[ 0.80603981 -0.21456876  0.47271857 -0.35710388 -1.093413  ]
 [ 1.03609419 -0.55417347  1.59926617 -0.43003097 -0.61598533]
 [ 0.84522825 -0.2183467   0.5043003   0.90745598  1.56870425]
 [-2.31897712  0.31366342 -0.65608186  0.75571901  0.23725617]]
weight_2: 
[[-0.89052844  0.32948658  0.32773978]
 [ 0.40159386 -1.07772005  2.24560618]
 [ 0.66951072  0.25132018 -0.68593705]
 [-1.10515797  1.34196305  0.44815379]
 [-2.69940996 -0.06878625  1.24937367]]
-------------------------Training Result------------------------------------------
                                                                                 
losses after per 1000 iteration:  0.324689
losses after per 1000 iteration:  0.0356117
losses after per 1000 iteration:  0.0224626
losses after per 1000 iteration:  0.0180354
losses after per 1000 itera