In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
data_path = "/home/aquib/Desktop/Iris.csv"

In [2]:
def read_data():
    data = pd.read_csv(data_path)
    x_lables = np.array(data.iloc[0:150,[1,2,3,4]].values)
    y_lable = data.iloc[0:150,[5]].values
    
    y = []
    value = []
    for i in y_lable:
        if i not in value:
            value.append(i)

    for i in y_lable:
        y.append(value.index(i))
        
    y_lable = pd.get_dummies(y)
    return x_lables,y_lable

    
read_data()

(array([[ 5.1,  3.5,  1.4,  0.2],
        [ 4.9,  3. ,  1.4,  0.2],
        [ 4.7,  3.2,  1.3,  0.2],
        [ 4.6,  3.1,  1.5,  0.2],
        [ 5. ,  3.6,  1.4,  0.2],
        [ 5.4,  3.9,  1.7,  0.4],
        [ 4.6,  3.4,  1.4,  0.3],
        [ 5. ,  3.4,  1.5,  0.2],
        [ 4.4,  2.9,  1.4,  0.2],
        [ 4.9,  3.1,  1.5,  0.1],
        [ 5.4,  3.7,  1.5,  0.2],
        [ 4.8,  3.4,  1.6,  0.2],
        [ 4.8,  3. ,  1.4,  0.1],
        [ 4.3,  3. ,  1.1,  0.1],
        [ 5.8,  4. ,  1.2,  0.2],
        [ 5.7,  4.4,  1.5,  0.4],
        [ 5.4,  3.9,  1.3,  0.4],
        [ 5.1,  3.5,  1.4,  0.3],
        [ 5.7,  3.8,  1.7,  0.3],
        [ 5.1,  3.8,  1.5,  0.3],
        [ 5.4,  3.4,  1.7,  0.2],
        [ 5.1,  3.7,  1.5,  0.4],
        [ 4.6,  3.6,  1. ,  0.2],
        [ 5.1,  3.3,  1.7,  0.5],
        [ 4.8,  3.4,  1.9,  0.2],
        [ 5. ,  3. ,  1.6,  0.2],
        [ 5. ,  3.4,  1.6,  0.4],
        [ 5.2,  3.5,  1.5,  0.2],
        [ 5.2,  3.4,  1.4,  0.2],
        [ 4.7,

In [3]:
x_lables, y_lable = read_data()

X_input = tf.placeholder(tf.float32, [None,4])
y_output = tf.placeholder(tf.float32, [None,3])


w1 = tf.Variable(tf.random_normal([4,5]), name = "Weights_1")
b1 = tf.Variable(tf.random_normal([1,5]), name = "Bias_1")

w2 = tf.Variable(tf.random_normal([5,3]),  name = "Weights_2")
b2 = tf.Variable(tf.random_normal([1,3]), name = "Bias_2")
#print "weight_2 before Iteration: ",w2

In [4]:
hidden_layer = tf.nn.sigmoid(tf.matmul(X_input,w1)+b1)
output_layer = tf.nn.softmax(tf.matmul(hidden_layer,w2) + b2)

losses = tf.losses.mean_squared_error(y_lable,output_layer)

#optimizer = tf.train.AdamOptimizer(0.001).minimize(losses)
optimizer = tf.train.GradientDescentOptimizer(0.09).minimize(losses)

sess = tf.InteractiveSession()
init = tf.global_variables_initializer()
sess.run(init)
print "************************weights before training*********************************"
print "                                                                                "


we1,we2 = sess.run([w1,w2])
print "weight_1: "
print we1
print "weight_2: "
print we2

print "-------------------------Training Result------------------------------------------"
print "                                                                                 "

step_size = 10000
for step in range(step_size):
    
    a,b,c,d,e,f = sess.run([hidden_layer,output_layer,losses,optimizer,w1,w2], feed_dict={X_input:x_lables,y_output:y_lable})

    if step%2000==0:
        print "losses after per 1000 iteration: ",c

print "                                                                                         "       
correct_prediction = tf.equal(tf.argmax(output_layer,1), tf.argmax(y_output,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print "-------------------------------------Accuracy--------------------------------------------"
print "                                                                                         "

print "Accuracy on the model: ",accuracy.eval(feed_dict={X_input:x_lables, y_output:y_lable})

check = tf.nn.sigmoid(tf.matmul([[6.8,3.2,5.9,2.3]],w1)+b1)
output = tf.nn.softmax(tf.matmul(check,w2) + b2)

print "***************************** weight after training *************************************"
print "weight_1 after trainig: "
print e
print "weight_2 after training: "
print f

a,b = sess.run([check,output])
#print (output)
print "-------------------------------------Results--------------------------------------------"
print "                                                                                         "
print "Result:  ",b


************************weights before training*********************************
                                                                                
weight_1: 
[[-1.06670809  1.42747211 -0.93775493 -1.62082124  1.34094393]
 [ 1.3183161   0.1441863  -1.81486189 -0.12378923 -0.62717527]
 [-0.36196601 -0.30769157 -0.43646875  1.05228233 -0.09818513]
 [ 0.85040385  1.34288156  0.86009032 -0.50265473  1.93989444]]
weight_2: 
[[-0.46068481 -0.85009849 -1.35885608]
 [-1.60727787 -1.84002161 -0.35146952]
 [ 1.22007835 -0.20734677  1.26633024]
 [ 0.63400757  1.12092662 -1.47261846]
 [-1.02548909  1.02697837 -0.75949943]]
-------------------------Training Result------------------------------------------
                                                                                 
losses after per 1000 iteration:  0.282865
losses after per 1000 iteration:  0.11148
losses after per 1000 iteration:  0.0487605
losses after per 1000 iteration:  0.0245723
losses after per 1000 iterati