In [29]:
import tensorflow as tf
import pandas as pd
import numpy as np
import itertools
data_path = "/home/aquib/Desktop/Iris.csv" #path to your data

In [22]:
def read_data():
    data = pd.read_csv(data_path) #read the data
    data = data.reindex(np.random.permutation(data.index)) #shuffling the data

    x_lables = np.array(data.iloc[0:150,[1,2,3,4]].values) 
    y_lable = data.iloc[0:150,[5]].values
    
    y = []
    value = []
    for i in y_lable:
        if i not in value:
            value.append(i)

    for i in y_lable:
        y.append(value.index(i))
        
    y_lable = pd.get_dummies(y)
    return x_lables,y_lable

    
read_data()

(array([[ 6. ,  2.2,  4. ,  1. ],
        [ 6.3,  3.3,  6. ,  2.5],
        [ 5.7,  2.9,  4.2,  1.3],
        [ 5. ,  2.3,  3.3,  1. ],
        [ 4.9,  3. ,  1.4,  0.2],
        [ 4.7,  3.2,  1.6,  0.2],
        [ 6.4,  3.1,  5.5,  1.8],
        [ 6.5,  3. ,  5.5,  1.8],
        [ 5. ,  3.6,  1.4,  0.2],
        [ 7.1,  3. ,  5.9,  2.1],
        [ 4.9,  3.1,  1.5,  0.1],
        [ 7.4,  2.8,  6.1,  1.9],
        [ 6.4,  2.8,  5.6,  2.2],
        [ 5.6,  3. ,  4.1,  1.3],
        [ 5.2,  4.1,  1.5,  0.1],
        [ 5.8,  2.6,  4. ,  1.2],
        [ 6. ,  3.4,  4.5,  1.6],
        [ 6.8,  3.2,  5.9,  2.3],
        [ 6.3,  2.9,  5.6,  1.8],
        [ 6.4,  3.2,  4.5,  1.5],
        [ 5.1,  3.8,  1.9,  0.4],
        [ 5.7,  2.5,  5. ,  2. ],
        [ 5. ,  3.4,  1.5,  0.2],
        [ 5.6,  2.5,  3.9,  1.1],
        [ 7.7,  3. ,  6.1,  2.3],
        [ 5.8,  2.7,  4.1,  1. ],
        [ 5.1,  3.8,  1.5,  0.3],
        [ 5.4,  3.9,  1.7,  0.4],
        [ 4.8,  3.1,  1.6,  0.2],
        [ 5.7,

In [23]:
x_lables, y_lable = read_data()

X_input = tf.placeholder(tf.float32, [None,4]) #creating palce holder for the holding the input value data will be feed during runtime
y_output = tf.placeholder(tf.float32, [None,3]) #creating placeholder for holding the actual label the data will feed during the run time


w1 = tf.Variable(tf.random_normal([4,5]), name = "Weights_1") #Initaliazing weight_1
b1 = tf.Variable(tf.random_normal([1,5]), name = "Bias_1")

w2 = tf.Variable(tf.random_normal([5,3]),  name = "Weights_2") #Initaliazing weight_2
b2 = tf.Variable(tf.random_normal([1,3]), name = "Bias_2")
#print "weight_2 before Iteration: ",w2
ind = sess.run(tf.argmax([0.021,0.0211,0.955]))
print ind


2
[ 0.  0.  1.]


In [28]:
hidden_layer = tf.nn.sigmoid(tf.matmul(X_input,w1)+b1) 
output_layer = tf.nn.softmax(tf.matmul(hidden_layer,w2) + b2)

losses = tf.losses.mean_squared_error(y_lable,output_layer)

#optimizer = tf.train.AdamOptimizer(0.001).minimize(losses)
optimizer = tf.train.GradientDescentOptimizer(0.09).minimize(losses)

sess = tf.InteractiveSession()
init = tf.global_variables_initializer()
sess.run(init)
print "************************weights before training*********************************"
print "                                                                                "


we1,we2 = sess.run([w1,w2])
print "weight_1: "
print we1
print "weight_2: "
print we2

print "-------------------------Training Result------------------------------------------"
print "                                                                                 "

step_size = 10000
for step in range(step_size):
    
    a,b,c,d,e,f = sess.run([hidden_layer,output_layer,losses,optimizer,w1,w2], feed_dict={X_input:x_lables,y_output:y_lable})

    if step%2000==0:
        print "losses after per 1000 iteration: ",c

print "                                                                                         "       
correct_prediction = tf.equal(tf.argmax(output_layer,1), tf.argmax(y_output,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print "-------------------------------------Accuracy--------------------------------------------"
print "                                                                                         "

print "Accuracy on the model: ",accuracy.eval(feed_dict={X_input:x_lables, y_output:y_lable})

check = tf.nn.sigmoid(tf.matmul([[6.8,3.2,5.9,2.3]],w1)+b1)
output = tf.nn.softmax(tf.matmul(check,w2) + b2)

print "***************************** weight after training *************************************"
print "weight_1 after trainig: "
print e
print "weight_2 after training: "
print f


a,b = sess.run([check,output])
#b = sess.run(output)
print "-------------------------------------Results--------------------------------------------"
print "                                                                                         "
#print "Result:  ",b
convert_list = list(itertools.chain.from_iterable(b))
print convert_list
indx = sess.run(tf.argmax(convert_list))

if(indx==0):
    print "Flower_Iris_Setosa"
elif(indx==1):
    print "Flower_Iris_Versicolor"
else:
    print "Flower_Iris_viginica"

************************weights before training*********************************
                                                                                
weight_1: 
[[-0.36223677  1.0483427   1.51492834  1.50437832  1.02970684]
 [-1.29111505  1.18258226 -0.07117686 -0.62687248 -0.50846922]
 [ 0.83629131 -1.49257708 -1.87965834 -0.20897792  2.74964333]
 [ 0.65472949 -0.24392195  0.20410123 -0.06860816 -0.22591133]]
weight_2: 
[[ 1.30150247  0.18346155  1.51761091]
 [ 1.12819791  1.30550289  0.07093971]
 [-1.29603589  0.33217216  0.46735194]
 [-1.35928988 -0.41526243  0.28635716]
 [-0.91610318  0.27905968 -1.05662942]]
-------------------------Training Result------------------------------------------
                                                                                 
losses after per 1000 iteration:  0.261651
losses after per 1000 iteration:  0.0542542
losses after per 1000 iteration:  0.0252577
losses after per 1000 iteration:  0.0186576
losses after per 1000 itera